In [590]:
import pandas as pd
import numpy as np
from astropy import units
from astropy.coordinates import SkyCoord, Distance
from astropy.cosmology import WMAP9
import datetime

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('default')

In [627]:
df = pd.read_csv('Rubin_data.csv')

df = df.loc[(df['Days_Since_Start'].notnull()) & \
              (df['RA'].notnull()) & \
              (df['Dec'].notnull()) & \
              (df['skybrightness'].notnull()) & \
              (df['moonphase'].notnull()) & \
              (df['filter'].notnull())] 
df

,Unnamed: 0,Days_Since_Start,RA,Dec,skybrightness,moonphase,cloud,airmass,filter
0,0,-1.791486e-07,294.696105,4.470982,18.304678,42.296595,0.0,1.216566,g
1,50,2.207091e-02,315.147446,-50.445865,18.530188,42.403654,0.0,1.080051,g
2,100,4.286855e-02,310.750035,-68.862225,18.364862,42.509076,0.0,1.279886,g
3,150,6.384219e-02,321.326185,-44.140467,18.577686,42.621052,0.0,1.031300,g
4,200,8.485535e-02,320.993922,-62.831260,18.439284,42.739344,0.0,1.188577,g
...,...,...,...,...,...,...,...,...,...
43607,2180350,3.652300e+03,64.503542,-33.170697,22.254113,19.718625,0.0,1.055799,z
43608,2180400,3.652322e+03,54.605726,-12.230438,22.154158,19.569410,0.0,1.053610,z
43609,2180450,3.652346e+03,41.874745,-15.042425,21.095537,19.419849,0.0,1.079142,z
43610,2180500,3.652370e+03,48.871737,-7.585806,20.288312,19.274071,0.0,1.142958,z
43611,2180550,3.652392e+03,92.539052,-2.643774,20.207910,19.152956,0.0,1.176380,z

In [628]:
x = []
y = []
z = []


distance = 100#arbitrary distance 
c1 = SkyCoord(df['RA'], df['Dec'], unit=(units.hourangle, units.deg), distance=distance*units.Mpc).galactic.cartesian

x = (c1.x.to(units.Mpc).value)
y = (c1.y.to(units.Mpc).value)
z = (c1.z.to(units.Mpc).value)

In [630]:
obsv = {
        'Days_Since_Start': df['Days_Since_Start'],
        'x': x,
        'y': y,
        'z': z,
        'skybrightness': df['skybrightness'],
        'moonphase': df['moonphase'],
        'cloud': df['cloud'],
        'airmass':df['airmass'],
        'filter':df['filter']
        }

df = pd.DataFrame(obsv, columns= [ 'Days_Since_Start','x','y','z','skybrightness','moonphase','cloud','airmass','filter'])


df

,Days_Since_Start,x,y,z,skybrightness,moonphase,cloud,airmass,filter
0,-1.791486e-07,-88.416121,-46.717812,-0.188667,18.304678,42.296595,0.0,1.216566,g
1,2.207091e-02,-5.887552,-57.008340,-81.947458,18.530188,42.403654,0.0,1.080051,g
2,4.286855e-02,53.378367,-47.643507,-69.863053,18.364862,42.509076,0.0,1.279886,g
3,6.384219e-02,-3.673047,-99.706919,6.711116,18.577686,42.621052,0.0,1.031300,g
4,8.485535e-02,16.568273,-96.769759,-19.002792,18.439284,42.739344,0.0,1.188577,g
...,...,...,...,...,...,...,...,...,...
43607,3.652300e+03,95.797427,-22.248922,18.106308,22.254113,19.718625,0.0,1.055799,z
43608,3.652322e+03,-73.193601,-66.377890,-15.384167,22.154158,19.569410,0.0,1.053610,z
43609,3.652346e+03,97.036356,21.984415,10.031509,21.095537,19.419849,0.0,1.079142,z
43610,3.652370e+03,-18.499406,27.871623,-94.238764,20.288312,19.274071,0.0,1.142958,z
43611,3.652392e+03,67.524424,61.975441,-39.993710,20.207910,19.152956,0.0,1.176380,z

In [631]:
df.to_csv(r'/Users/candicestauffer/desktop/VIS_proj/src/data/Cart_Rubin_data.csv', index = True)

In [632]:
c_test = SkyCoord(0,90, unit=(units.hourangle, units.deg), distance=distance*units.Mpc).galactic.cartesian
x = (c_test.x.to(units.Mpc).value)
y = (c_test.y.to(units.Mpc).value)
z = (c_test.z.to(units.Mpc).value)
print (x,y,z)

print (x/-48.383507361671555)
print (y/74.69821839866675)

#these values need to be added to the x y and z values so it will fit the grid. (see code above)

-48.383507361671555 74.69821839866675 45.59838136873016
1.0
1.0

SyntaxError: invalid syntax (<ipython-input-626-225eb93c5fd4>, line 1)